export const DOCUMENT_DEFAULT_PAGE = 1;
export const DOCUMENT_DEFAULT_LIMIT = 20;

export const DOCUMENT_MAX_FILES_PER_DOCUMENT = 10;
export const DOCUMENT_MAX_PAGE_NO = DOCUMENT_MAX_FILES_PER_DOCUMENT;

export const DOCUMENT_TAG_NAME_MAX_LENGTH = 30;
