export enum ERROR_CODE {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  EMAIL_ALREADY_USED = 'EMAIL_ALREADY_USED',
  NICKNAME_ALREADY_USED = 'NICKNAME_ALREADY_USED',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  INVALID_TOKEN = 'INVALID_TOKEN',
  EMAIL_SEND_FAILURE = 'EMAIL_SEND_FAILURE',
  INVALID_EMAIL_VERIFICATION = 'INVALID_EMAIL_VERIFICATION',
  NOTIFICATION_NOT_FOUND = 'NOTIFICATION_NOT_FOUND',
  DEVICE_TOKEN_NOT_FOUND = 'DEVICE_TOKEN_NOT_FOUND',
}
